### ISSUE TITLE
can't find module react node_modules/react-chartkick

### ISSUE THREAD

**Issue by GitHubJiKe** [ankane/react-chartkick#10]
I use this library with create-react-app, when I installed this library ,I can't use yarn start ,because react-scripts was deleted, and then I reinstalled to start my app ,but there's a error with  node_modules/react-chartkick : **index.css?f255:26 Uncaught Error: Cannot find module "react"**

**Comment by ankane** [comment]
Hey @GitHubJiKe, this doesn't sound like an issue with React Chartkick.
