### ISSUE TITLE
"Loading text" isn't being removed

### ISSUE THREAD

**Issue by Sexual** [ankane/react-chartkick#12]
For whatever reason when using Highcharts and react-chartkick, the chart is loaded but the "Loading..." text remains causing the graph to be pushed out of the parent element.

![2e0cksd0tteu1z7zpmq4ia](https://user-images.githubusercontent.com/8002719/33294772-09b934d6-d3ca-11e7-97f0-8377254dbe45.png)

**Comment by ankane** [comment]
Hey, thanks for reporting. Do you have two charts with the same id by any chance?

**Comment by Sexual** [comment]
Nope, only got one chart. Even tried adding a completely random ID.

**Comment by Sexual** [comment]
I've actually experimented a bit more, this looks like an issue with the chart trying to render an empty object/array before the content has been fetched and then for whatever reason the once the data is loaded, the loading text of the previous chart isn't being removed.

**Comment by ankane** [comment]
Thanks for the update. I'll try to repo with a refresh app.

**Comment by ankane** [comment]
Should be fixed by #16. Thanks for reporting @Sexual
