### ISSUE TITLE
[Question] Dataset Properties?

### ISSUE THREAD

**Issue by jordanoverbye** [ankane/react-chartkick#13]
Hello, is it possible to set any chart js dataset properties? (http://www.chartjs.org/docs/latest/charts/line.html#dataset-properties). It seems like you can only set label(name) and data.

For example: 

```
data = [
  {
  	"name":"Workout", 
  	"data": {"2017-01-01": 3, "2017-01-02": 4}},
  	"backgroundColor": "#00ff00",
  	"borderWidth": "5",
  }, {
  	...
  }
];

<LineChart data={data} />
```

**Comment by ankane** [comment]
Hey @jordanoverbye, it's not currently documented, but you can add a `library` option on the same level as `name` and `data` to set dataset properties for Chart.js.

**Comment by ankane** [comment]
Cleaning up stale issues. Hope the recommendation above helped @jordanoverbye

**Comment by jordanoverbye** [comment]
Thanks ankane!
