### ISSUE TITLE
Create-React-App Fails to Minify

### ISSUE THREAD

**Issue by ilrein** [ankane/react-chartkick#14]
The aforementioned toolset for spinning up React apps fails to compile for production this package.

The exact message:

```
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

 	./~/react-chartkick/index.js:14 
```

Looking at the code, it seems to throw an err at the first arrow function:

```
var createComponent = (chartType) => {
```

It's referenced in the README to this issue: https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

Basically the package is published and the "main" of package.json references the non-babel transpiled code. This package won't work unless an ES5 version is the main export.

**Comment by ankane** [comment]
Hey @ilrein, thanks for the detailed report 💯  Fixed on master. Will push out a new release later tonight.

**Comment by BernardoFBBraga** [comment]
Hey @ankane I'm still getting this error on 0.1.7

**Comment by BernardoFBBraga** [comment]
hey @ankane I'm getting this error on 0.1.7 however the error points to ./node_modules/chartkick/src/helpers.js:15
I'm not sure if I should go to chartkick to request this as they are not really concerend about react and create-react-app

**Comment by BernardoFBBraga** [comment]
just realized both projects are yours

**Comment by ankane** [comment]
Make sure you’re on the latest chartkick (2.3.4)

**Comment by ankane** [comment]
Fixed in https://github.com/ankane/chartkick.js/pull/97

**Comment by BernardoFBBraga** [comment]
Github says last version is 2.3.3, which confused me. I updated the package.json and it worked thanks

**Comment by ankane** [comment]
Where does it show that?
