### ISSUE TITLE
Can't get this working in CodeSandbox

### ISSUE THREAD

**Issue by JikkuJose** [ankane/react-chartkick#15]
Complains: 'No adapter found'

https://codesandbox.io/s/l26p4r5qjq

**Comment by ankane** [comment]
Hey @JikkuJose, you need to select a charting library and make sure it's installed correctly. Instructions are here: https://github.com/ankane/react-chartkick#installation

**Comment by JikkuJose** [comment]
Adding it as a dependency won't work? I should have the charting library as a link tag in head?

**Comment by ankane** [comment]
@JikkuJose No, simply adding it as a dependency won't work. You need to follow the complete instructions as laid out in the readme.

**Comment by findjashua** [comment]
adding `import Chart from 'chart.js'` resolved the issue for me

**Comment by JikkuJose** [comment]
@ankane excuse me, but adding the dependency via `window` seems to be a hack? Or perhaps its my mental model thats wrong?

**Comment by ankane** [comment]
@JikkuJose Happy to take suggestions for a better approach, but that's what you'll need to do for now.
