### ISSUE TITLE
Google Charts props

### ISSUE THREAD

**Issue by zeagord** [ankane/react-chartkick#19]
How can I props like data "type", visualization, background color? What are the supported props?

**Comment by ankane** [comment]
Hey @zeagord, what have you tried?

**Comment by zeagord** [comment]
I was trying the Google timeline charts. I want to know the list supported props, how can change the unit of the chart, etc. For example, the one in the documentation has date as a unit, what if i want to change the unit to hours or just numbers.

`<Timeline data={[["Washington", "1789-04-29", "1797-03-03"], ["Adams", "1797-03-03", "1801-03-03"]]} />
`

**Comment by ankane** [comment]
@zeagord if it’s not possible with the library option, you’re better off using Google Charts directly.

**Comment by zeagord** [comment]
Thank you.
