### ISSUE TITLE
Webpack Build Issue

### ISSUE THREAD

**Issue by DinakaranS** [ankane/react-chartkick#20]
Hi 
I am getting following issue while building webpack

ERROR in bundle.js from UglifyJs
Unexpected token: name (key) [./node_modules/chartkick/src/helpers.js:15,0][bundle.js:257776,6]

Thanks
Dinakaran S

**Comment by ankane** [comment]
Hey @DinakaranS, can you give more detail on your setup? Things like:

1. The versions of chartkick and react-chartkick you're on
2. The full backtrace
3. Code to reproduce

**Comment by DinakaranS** [comment]
Hi ankane,
I am using  "webpack" version 3.4.1, "webpack-dev-server" version 2.4.5, "chartkick" version 2.3.3 and  "react-chartkick" version 0.1.6

In my .babelrc i use {"presets": ["react", "es2015", "stage-1"]}

Webpack configuration will be like 

const JS_REGEX = /\.js$|\.jsx$|\.es6$|\.babel$/;
const webpack = require('webpack');

module.exports = {
    devtool: 'source-map',
    entry: ['babel-polyfill',
        './src/index.js'
    ],
    output: {
        path: __dirname,
        publicPath: '/',
        filename: 'bundle.js'
    },
    module: {
        loaders: [
            {test: /\.json$/, loader: 'json-loader'},
            {test: JS_REGEX, exclude: /node_modules/, loader: 'babel-loader'},
            {
                test: /\.scss$/,
                exclude: /node_modules/,
                loaders: ["style-loader", "css-loader?sourceMap!sass-loader?sourceMap"]
            },
            {
                test: /\.(jpe?g|png|gif|svg)$/i,
                loaders: [
                    'file?hash=sha512&digest=hex&name=[hash].[ext]',
                    'image-webpack?bypassOnDebug&optimizationLevel=7&interlaced=false'
                ]
            },
        ],
    },
    resolve: {
        extensions: ['*', '.js', '.jsx']
    },
    node: {
        console: true,
        fs: 'empty',
        net: 'empty',
        tls: 'empty',
        dns: 'empty'
    },
    plugins: [
        new webpack.optimize.ModuleConcatenationPlugin(),
        new webpack.HotModuleReplacementPlugin(),
        new webpack.NoEmitOnErrorsPlugin(),
        new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/),
        new webpack.DefinePlugin({
            'process.env': {
                // This has effect on the react lib size
                'NODE_ENV': JSON.stringify('production'),
            }
        }),
        new webpack.optimize.UglifyJsPlugin({
            sourceMap: true
        })
    ],
    devServer: {
        historyApiFallback: true,
        contentBase: './'
    }
};

**Comment by ankane** [comment]
Thanks @DinakaranS. Unfortunately, I don't know off the top of my head and don't have the bandwidth to dig in. Here's a similar issue that might have the answer: https://github.com/joeeames/WebpackFundamentalsCourse/issues/3

I'll leave this open in case someone else has an idea. Please update the issue if you find anything or figure it out, so others having the same issue can benefit.

**Comment by timrogers** [comment]
I'm hitting this. I've tried installing the latest `uglifyjs-webpack-plugin` which seems to be the most common solution, but it's still not happy.

**Comment by jaylocke** [comment]
I had the same problem. How to do solve that?

**Comment by timrogers** [comment]
The underlying change to Webpacker is mentioned [here](https://github.com/rails/webpacker/blob/master/CHANGELOG.md#breaking-changes-2) - it's not terribly easy to understand the impact from reading it though!

**Comment by wpp** [comment]
Thanks so much for sharing your work-around @timrogers! I had the same issue and resolved it with the fallback to the `uglifyjs-webpack-plugin` too.

**Comment by ankane** [comment]
Just pushed a new version that uses the `module` option in `package.json`, which may fix it. Let me know.

**Comment by wpp** [comment]
0.2.0 seems to work for me. Thanks

**Comment by ankane** [comment]
Great to hear
