### ISSUE TITLE
Is possible to customize tooltip?

### ISSUE THREAD

**Issue by JeffersonFilho** [ankane/react-chartkick#23]
Thanks for taking your time making this lib!

I was wondering if is possible to customize the tooltip on the Google charts.

I wanted to change 'Votes: 100' to 'Votes: 100%', is that possible?

https://gyazo.com/0fca315355cf32638df068b9690c4428

Thanks!

**Comment by JeffersonFilho** [comment]
I made a PR dor this: https://github.com/ankane/chartkick/pull/426

**Comment by ankane** [comment]
For reference, discussion at https://github.com/ankane/chartkick.js/pull/95
