### ISSUE TITLE
Remove deprecated React.createClass

### ISSUE THREAD

**Issue by ankane** [ankane/react-chartkick#3]
For React 16

**Comment by ramboza** [comment]
+1

**Comment by jnsoo123** [comment]
+1

**Comment by inergy** [comment]
@ankane PR submitted for this ( #8 )

**Comment by inergy** [comment]
@ankane can you check #9 for this issue?

**Comment by spq24** [comment]
@ankane will you accept the PR from @inergy ? Trying to put this into a project and getting an error.

**Comment by ankane** [comment]
Version 0.1.4 was just released to add support for this.

**Comment by spq24** [comment]
thanks @ankane appreciate it.
