### ISSUE TITLE
Y-axis values get changed

### ISSUE THREAD

**Issue by chrise86** [ankane/react-chartkick#30]
I apologise in advance if this ends up being blatant user error, but it's been driving me mad.

The data seems to load and then jump around, which results in the y-axis values being out of order. I've attached a gif to show what happens.

![chartjs](https://user-images.githubusercontent.com/616956/46172475-7432b600-c29b-11e8-94f3-00be912dbf14.gif)

All data passed to the chart is actually in the correct order, so I have no idea why it's switching.

Any idea why this would happen?

**Comment by ankane** [comment]
Hey @chrise86, haven't seen that before. Did you figure it out? If not, can you add code to reproduce?

**Comment by chrise86** [comment]
@ankane I'm not exactly sure why this was happening, but I think it's possibly due to the way object keys are handled.

It turns out that when using an array of objects, even though the objects remained the same, re-renders would cause the graph to jump about. I managed to mitigate this by using an array of arrays instead.

**Comment by ankane** [comment]
JavaScript doesn't guarantee ordering for objects, so that's likely the cause. https://stackoverflow.com/questions/5525795/does-javascript-guarantee-object-property-order

**Comment by chrise86** [comment]
Yeh I understand that, it’s just odd how the object wasn’t changing, so the prop to the graph component shouldn’t have changed, yet it was still re-rendering and losing its ordering.

Also, I _believe_ that object property order behaviour is changing 🤔
