### ISSUE TITLE
Donut chart data structure

### ISSUE THREAD

**Issue by chrise86** [ankane/react-chartkick#32]
I'm trying to replicate [this example](http://www.chartjs.org/samples/latest/charts/doughnut.html) with 2 datasets. I have set the correct adapter, and my data is currently as follows:

```
<PieChart
  stacked
  donut={true}
  data={[{
    name: 'US',
    data: [
      ['Demand', usDemand],
      ['Spares', usSpares],
      ['Backups', usBackups]
    ]
  }, {
    name: 'CA',
    data: [
      ['Demand', caDemand],
      ['Spares', caSpares],
      ['Backups', caBackups]
    ]
  }, {
    name: 'ROW',
    data: [
      ['Demand', rowDemand],
      ['Spares', rowSpares],
      ['Backups', rowBackups]
    ]
  }]}
  colors={['#305994', '#69CA7E', '#8B59C8', '#AAAAAA']}
/>
```
and I'm already getting a blank chart. When I inspect the React component with dev tools the data prop looks like this:

![screenshot 2018-10-25 at 11 59 50](https://user-images.githubusercontent.com/616956/47495998-904f5600-d84d-11e8-9f60-f523f5d5bef0.png)

I have tried with and without the `stacked` prop. Can you explain how to do this please?

**Comment by ankane** [comment]
Cleaning up stale issues
