### ISSUE TITLE
Donut chart no labels

### ISSUE THREAD

**Issue by elroychibex** [ankane/react-chartkick#34]
Hi, I created a donut chart in react, but I noticed that the values don't display when you hover over a section of the chart.
Meanwhile, in the doc examples the labels appear. What could be wrong?

`<PieChart
![urea](https://user-images.githubusercontent.com/24192238/47615295-554b5d80-daad-11e8-885c-60905ff2491b.png)

        data={[["Allocated", 45], ["Distributed", 20], ["Undistributed/Intransit", 25], ["In Store", 10]]} 
        donut={true}  legend={false} colors={["#9ACA3D", "#2A91CB", "#EAFF00", "#C4C4C4"]} messages={{empty: "Fetching data..."}}
        library={{cutoutPercentage: 30}} dataset={{borderWidth: 0}} width="80px" height="80px" label="Value" />`

**Comment by ankane** [comment]
Hey @elroychibex, I'd make sure you don't have any elements on top of the chart. The hover labels show up fine for me with that code.

**Comment by elroychibex** [comment]
Thanks. I have found the issue. I had z-index: -1 set in the content area. Removed that and it worked fine.
