### ISSUE TITLE
[Idea] Customize axis label color / fonts

### ISSUE THREAD

**Issue by brettmeyer** [ankane/react-chartkick#38]
Thanks for the work on this project, wondering if you could add the options to change in axis labels via the options, like you have set the height option, for example:

```
      var props = this.props;
      var style = {
        height: props.height || "300px",
        lineHeight: props.height || "300px",
        width: props.width || "100%",
        textAlign: "center",
        color: props.axisColor || "#999",
        fontSize: "14px",
        fontFamily: "'Lucida Grande', 'Lucida Sans Unicode', Verdana, Arial, Helvetica, sans-serif"
      };
```

**Comment by ankane** [comment]
Hey @brettmeyer, what do you think the interface should look like for that?

**Comment by brettmeyer** [comment]
So I had these charts on a dark background and thought if you could pass another parameter into the JSX component to change the axis labels, for example:

`<LineChart axisTextColor="#ff0000" data={{"2017-05-13": 2, "2017-05-14": 5, ...}} />`

To change these colors:

![chart](https://user-images.githubusercontent.com/313806/52263345-91f1e500-2937-11e9-9ba7-3a203ea2155c.jpg)

**Comment by stevecastaneda** [comment]
Would love this!  On a darker background, you can barely see axis and I'm having trouble finding a CSS selector to edit it.

("MH" is the Y axis here, barely seen)

<img width="196" alt="image" src="https://user-images.githubusercontent.com/171488/52604662-5e302700-2e31-11e9-80af-23937b19026a.png">

**Comment by ankane** [comment]
Thanks, you should be able to use the `library` option for this. I don't think it's common enough to add a Chartkick option.

**Comment by stevecastaneda** [comment]
What would be the correct configuration for chart.js, to update the axis labels?  I've tried `<AreaChart data={data} ytitle="YTitle" library={{ labels: { fontColor: "#fff" } }} />` but no luck.

**Comment by brettmeyer** [comment]
I attempted this, but wasn't able to change any library options

**Comment by stevecastaneda** [comment]
Was able to get it to work:

```
library={{
            legend: {
              labels: {
                fontColor: "#fff"
              }
            },
            scales: {
              yAxes: [
                {
                  ticks: { fontColor: "#fff" },
                  scaleLabel: { fontColor: "#fff" }
                }
              ],
              xAxes: [
                {
                  ticks: { fontColor: "#fff" }
                }
              ]
            }
          }}
```

**Comment by lovato** [comment]
@stevecastaneda thanks. With your example, I was able to replace fontFamily, which was my problem.

**Comment by ankane** [comment]
Cleaning up issues
