### ISSUE TITLE
[Idea] Set id attribute

### ISSUE THREAD

**Issue by Caelesis** [ankane/react-chartkick#44]
Hi,

Thanks for your work.

I'm currently trying to implement this lib in Gutenberg (WordPress) to create some nice charts. All is OK except a little thing. Guntenberg find a difference between markup of the save function and the front end returning markup. This difference is about the chart "id" attribute which they're not equal for back and front.
Is it possible to add a config param to set the ID ? The ID could be choose from the back end and use for id attribute.

Thanks for your help and for your work!

**Comment by ankane** [comment]
Hey @Caelesis, not sure I fully understand. You can already set the `id` of a chart. https://github.com/ankane/react-chartkick#options

**Comment by Caelesis** [comment]
Sorry for disturbing, it's my bad, It works also with PieChart. Thanks for your quick reply, appreciated :wink:

**Comment by ankane** [comment]
No worries
