### ISSUE TITLE
Issue with dates and timezones

### ISSUE THREAD

**Issue by DemidenkoAndrey** [ankane/react-chartkick#47]
Hello!

I have an issue with dates and I suppose timezones.
Everything is ok when I use chartjs, but when I use highcharts all dates shiffted to 1 day back and label shows date with time.

See examples for same data:

Highcharts:
https://prnt.sc/q6oqrs
Chartjs:
https://prnt.sc/q6ork4

I suppose there is an issue with timezone, because my local timezone is GMT+3. And as you can see on highcharts it shows 21:00.

**Comment by ankane** [comment]
Hey @DemidenkoAndrey, thanks for reporting. Can you share an example of what the `data` prop looks like?

**Comment by DemidenkoAndrey** [comment]
@ankane 
`[..., ['2019-12-05',  1.14724884289812]]`
