### ISSUE TITLE
Viewport resize - React app

### ISSUE THREAD

**Issue by joconnor-dev** [ankane/react-chartkick#48]
When resizing the viewport (tested on chrome, firefox, and safari) the PieChart will resize correctly as it gets smaller, but will not resize when the viewport gets larger. Once I refresh the page, it will render the correct size. However, users that will be using this won't want to refresh the window every time they adjust the viewport larger in order for the chart to properly resize.

Original Size
![originalSize](https://user-images.githubusercontent.com/44309632/77810325-4c780600-706a-11ea-8255-15008b1f4250.png)

Shrink window
![smallerViewport](https://user-images.githubusercontent.com/44309632/77810327-4f72f680-706a-11ea-9cf8-39a853eb845c.png)

Resize to be larger
![largerViewportAfterShrinking](https://user-images.githubusercontent.com/44309632/77810330-513cba00-706a-11ea-898b-95636aea2617.png)

**Comment by ankane** [comment]
Hey @joconnor-dev, unfortunately, I'm not sure how to reproduce. The charts resize as expected on the [test page](https://github.com/ankane/react-chartkick/blob/master/test/index.html). I'd confirm the element that contains the chart is being properly resized.

**Comment by ankane** [comment]
Closing due to no response
