### ISSUE TITLE
use persian date instead of gregorian date or show my custom Text

### ISSUE THREAD

**Issue by tabeshR** [ankane/react-chartkick#50]
Hi,
I have a problem with Line Chart
I want to use persian date but I cant and It shows me gregorian date . what should I do ?
if it is impossible please let me know how can I show data with this sample : 1399/05/19
now it shows me 19 May 
and if I remove 1399 it works but I want to show the year also!
please help me
thanks alot

**Comment by ankane** [comment]
Hey @tabeshR, I don't have the bandwidth to help with specific customizations, but you should be able to use the `library` option for it.

**Comment by ankane** [comment]
Cleaning up issues
