### ISSUE TITLE
extraneous-dependencies error (eslint)

### ISSUE THREAD

**Issue by DanielRuf** [ankane/react-chartkick#53]
The eslint rule `import/no-extraneous-dependencies` throws an error because `chartkick` is not listed in `package.json` when you follow the setup steps.

**Comment by ankane** [comment]
Hey @DanielRuf, thanks for sharing. You can run `npm install chartkick` to fix, but prefer to keep the installation instructions simple.

**Comment by DanielRuf** [comment]
Well, the warning is there for good reasons.

> import 'chartkick/chart.js'

This will also fail with yarn v2 qnd probably future npm versions unless we run `npm i chartkick`. The current approach is not the ideal way.

**Comment by DanielRuf** [comment]
Well, the warning is there for good reasons.

> import 'chartkick/chart.js'

This will also fail with yarn v2 and probably future npm versions unless we run `npm i chartkick`. The current approach is not the ideal way.

**Comment by josecheo** [comment]
:D
